### ISSUE TITLE
Files > search feature not able to search directory name.

### ISSUE THREAD

**Issue by fenlasonb** [RetroShare/documentation#69]
Hey Guys

Was just wondering if there is any chance there would be able to be a patch maybe or next version to be able to search directory names when using the search feature in Files. I think this would really help as my friends and I are using this as a mesh network sharing solution but we cannot search file directories which in case all would have a directory called movies and then in movies we can then open directories from there.

Just an idea for a nice feature request.

:) 

cheers

**Comment by alfinal** [comment]
NOTE: That's not the place to publish this feature request.

**Comment by fenlasonb** [comment]
> NOTE: That's not the place to publish this feature request.

where would i post this feature request? Sorry new to this site.

**Comment by defnax** [comment]
here please : https://github.com/RetroShare/RetroShare/issues
