### ISSUE TITLE
Chat rooms disappear after reconnect

### ISSUE THREAD

**Issue by tiotrom** [RetroShare/documentation#70]
Operating System: Manjaro Gnome (up to date)
Retroshare version 0.6.5

To reproduce: create a chat room (private/public), disconnect then check the chats tab again. No room. Tested with several users (so we could reproduce it).

**Comment by G10h4ck** [comment]
In current chat room implementation, a chat room survive only until someone is connected to it

**Comment by csoler** [comment]
It would make lots of sense that the creator of the room saves it so that it can advertise it on next run automatically.

**Comment by tiotrom** [comment]
Hm I am wondering why is this the case. Forums or Channels are saved automatically. We wanted to migrate our projects from Riot to Retroshare but if chat rooms (what we used a lot in riot) are not automatically saved somehow, then is going to be tough if possible. Do you plan to make it so the chatrooms are saved like forums are? cheers and thanks for your work!

**Comment by G10h4ck** [comment]
We have dedicated a GSoC 2019 slot to chat improvements and this should be certainly included in that work ;)

**Comment by tiotrom** [comment]
That would be fantastic. This tool really looks promising. We are testing it more and more these days and will report here on github any bugs we find ;)

**Comment by csoler** [comment]
that can be implemented easily. If you can compile yourself, it should be done within a week. So watch the commits.

**Comment by tiotrom** [comment]
I'll do that. But I am afraid I won't know how to compile it myself...

**Comment by defnax** [comment]
place use the right place : https://github.com/RetroShare/RetroShare/issues
