### ISSUE TITLE
Cannot reconnect at all

### ISSUE THREAD

**Issue by tiotrom** [RetroShare/documentation#72]
I use Manjaro Gnome + latest retroshare.
I am behind a VPN with port forwarding. If I normally open retroshare it works with the default settings. If I then close it and reopen and select Manually Forwarded Port and add the right one, it fails to connect (says "NAT DHT disabled" and "DHT: No peer found in DHT"). Now, I try to put the settings back and select the default Automatic UPnP. I wait a long time and does not connect back. it says "NAT: DHT Disabled and Firewalled" and "DHT: No peer found in DHT".

Basically I am unable to reconnect again.

If I wipe all the config files and start as brand new, it will work though.

Any idea what is happening?

**Comment by G10h4ck** [comment]
This is the wrong place for this kind of issue, please open a new one under https://github.com/RetroShare/RetroShare/issues
