### ISSUE TITLE
Miss `build-essential` and `cmake` packages for Debian compilation dependencies

### ISSUE THREAD

**Issue by selankon** [RetroShare/documentation#74]
I'm not sure why but is miss the `build-essential` and `cmake` for Debian dependencies.

And I'm not sure at all but I think that maybe we should add the qt5-default, but maybe for compilation is not need.

PR: https://github.com/RetroShare/documentation/pull/73

**Comment by G10h4ck** [comment]
The most updated build scripts for linux distributions are found here https://github.com/RetroShare/OBS/  documentation on how to build it's always lagging behind while those scripts are updated regularly

**Comment by defnax** [comment]
wrong place 
https://github.com/RetroShare/RetroShare/issues
