### ISSUE TITLE
No build for Ubuntu 19.10

### ISSUE THREAD

**Issue by georgedorn** [RetroShare/documentation#78]
https://download.opensuse.org/repositories/network:/retroshare/xUbuntu_19.10/ is lacking a build of 
`retroshare_0.6.5_amd64.deb`.  I can work around it, but less savvy or more risk-averse users trying to follow download directions as written will run into a roadblock there.

**Comment by G10h4ck** [comment]
RetroShare 0.6.5 won't build with the libraries shipped with ubuntu 19.10, until we release 0.6.6 you can use the unstable package
