### ISSUE TITLE
Unable to produce executables while compilation of retroshare on ubuntu

### ISSUE THREAD

**Issue by AdB9** [RetroShare/documentation#84]
I'm using Ubuntu 18.4.02 LTS
I followed these steps: 

_Compile_
```
   cd trunk
   qmake CONFIG+=debug
   make

```

_Install_
`   sudo make install`

_The executables produced will be:_

/usr/bin/RetroShare06
/usr/bin/RetroShare06-nogui

**But these executables are not being produced.**

If I execute further commands, I get error on:
 ```
$ sudo make retroshare-nogui-install_subtargets

make: *** No rule to make target 'retroshare-nogui-install_subtargets'.  Stop.
```

What could be the reason  ?

**Comment by defnax** [comment]
wrong place here 
right place -> https://github.com/RetroShare/RetroShare/issues
